#define LIT_INTEGER                      1
#define TK_IDENTIFIER                    2
#define PNT_END_OF_STATEMENT             3
#define OP_PLUS                          4
#define OP_SUB                           5
#define OP_ASTERISK                      6
#define OP_DIV                           7
#define OP_MOD                           8
#define PNT_LEFT_PAREN                   9
#define PNT_RIGHT_PAREN                 10
