#define LIT_INTEGER                      1
#define TK_IDENTIFIER                    2
#define PNT_END_OF_STATEMENT             3
#define OP_ASSIGN                        4
#define TK_PRINT                         5
#define OP_PLUS                          6
#define OP_SUB                           7
#define OP_ASTERISK                      8
#define OP_DIV                           9
#define OP_MOD                          10
#define PNT_LEFT_PAREN                  11
#define PNT_RIGHT_PAREN                 12
